"""Write the vault's machine zones. Nothing else in the vault is touched.

    tcg/mtg/_generated/<deck>-data.md    regenerated every sync; stale ones removed
    tcg/mtg/_generated/collection-summary.md
    tcg/mtg/_log/prices.md               append-only, one snapshot per day
    tcg/mtg/_log/<deck>-versions.md      append-only, only when a list changes

Authored notes pull generated ones in with ![[aesi-lands-data]]. No dots in
generated names: Obsidian reads "aesi-lands.data" as a ".data" file.
"""

import hashlib
import json
from collections import Counter
from datetime import UTC, date, datetime
from pathlib import Path

from riffle.analysis.ownership import BUY, MARK, OWN, Row, summary
from riffle.analysis.pricing import DeckPrice
from riffle.config import data_dir
from riffle.models import Deck, Holding, Prices
from riffle.store import Catalog


def _money(x: float | None) -> str:
    return f"${x:,.2f}" if x is not None else "—"


def _tix(x: float | None) -> str:
    return f"{x:,.2f}" if x is not None else "—"


def _write(path: Path, text: str) -> bool:
    """Write only if different, so pCloud doesn't resync unchanged files."""
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    path.write_text(text, encoding="utf-8")
    return True


def deck_data(
    deck: Deck,
    rows: list[Row],
    dp: DeckPrice,
    unresolved: list[str],
    today: str,
    imports: dict[str, str] | None = None,
) -> str:
    s = summary(rows)
    buy = [(row, line) for row, line in zip(rows, dp.lines, strict=True) if row.status == BUY]
    out = [
        "---",
        f"title: {deck.slug}-data",
        "type: generated",
        f"deck: {deck.slug}",
        f"generated: {today}",
        "---",
        "",
        "> [!warning] Generated by `riffle sync` — edits here are overwritten",
        "",
        f"**{deck.count()} cards** · {MARK[OWN]} {s[OWN]} own · {MARK[BUY]} {s[BUY]} buy",
        "",
        "| | Paper | MTGO |",
        "|---|---|---|",
        f"| Whole deck | {_money(dp.usd_total)} | {_tix(dp.tix_total)} tix |",
        f"| Still to buy | {_money(dp.usd_to_buy)} | — |",
        "",
    ]
    if buy:
        out += ["## Buy", "", "| Buy | Card | Paper | MTGO |", "|---|---|---|---|"]
        for row, line in sorted(buy, key=lambda pair: -(pair[1].usd or 0)):
            note = f" (own {row.owned} of {row.needed})" if row.partial else ""
            out.append(
                f"| {MARK[BUY]} {row.shortfall} | [[{row.name}]]{note} "
                f"| {_money(line.usd)} | {_tix(line.tix)} |"
            )
        out.append("")
    if dp.missing_on_mtgo:
        out += ["## Not on MTGO", "", ", ".join(f"[[{n}]]" for n in dp.missing_on_mtgo), ""]
    if unresolved:
        out += ["> [!bug] Names that didn't match any card", "> " + ", ".join(unresolved), ""]
    for title, text in (imports or {}).items():
        out += [f"## {title}", "", "```", text.rstrip(), "```", ""]
    return "\n".join(out)


def collection_summary(holdings: list[Holding], catalog: Catalog, today: str) -> str:
    counted: list[tuple[str, Holding]] = []
    for h in holdings:
        if h.source == "manabox" and h.card_id:
            counted.append((h.card_id, h))
    total = sum(h.quantity for _, h in counted)
    unique = len({card_id for card_id, _ in counted})
    printed = catalog.printings({h.scryfall_id for _, h in counted if h.scryfall_id})
    own_price = [p.usd if (p := printed.get(h.scryfall_id or "")) else None for _, h in counted]
    cheapest = catalog.prices(
        {card_id for (card_id, _), usd in zip(counted, own_price, strict=True) if usd is None}
    )
    valued = []
    for (card_id, h), usd in zip(counted, own_price, strict=True):
        if usd is None:  # no price for the printing owned: value it as the card's cheapest
            usd = cheapest.get(card_id, Prices()).usd
        valued.append((usd or 0) * h.quantity)
    top = sorted(zip(valued, counted, strict=True), key=lambda x: -x[0])[:15]
    lines = [
        "---",
        "title: collection-summary",
        "type: generated",
        f"generated: {today}",
        "---",
        "",
        "> [!warning] Generated by `riffle sync` — edits here are overwritten",
        "",
        f"**{total:,} cards · {unique:,} unique · ~{_money(sum(valued))}** (ManaBox export)",
        "",
    ]
    lines += ["## Most valuable", "", "| Card | Copies | Value |", "|---|---|---|"]
    lines += [f"| [[{catalog.name(card_id)}]] | {h.quantity} | {_money(v)} |" for v, (card_id, h) in top]
    return "\n".join(lines) + "\n"


def append_prices(log: Path, cards: list[tuple[str, float | None, float | None]], today: str) -> int:
    log.parent.mkdir(parents=True, exist_ok=True)
    if not log.exists():
        log.write_text(
            "---\ntitle: prices\ntype: log\n---\n\n# Price log\n\n"
            "Appended by `riffle sync` for every unticked #mtg/buy card. Never edit.\n\n"
            "`date | card | paper | tix`\n\n",
            encoding="utf-8",
        )
    existing = log.read_text(encoding="utf-8")
    if f"\n{today} | " in existing:
        return 0
    with log.open("a", encoding="utf-8") as f:
        for name, usd, tix in sorted(cards):
            f.write(f"{today} | {name} | {_money(usd)} | {_tix(tix)}\n")
    return len(cards)


def _state_path() -> Path:
    return data_dir() / "sync-state.json"


class Unreadable(ValueError):
    """sync-state.json is there but can't be read."""


def load_state() -> dict:
    """Each deck's list at the last sync that logged it, by slug: what version logs diff
    against. Empty before the first sync; Unreadable if the file can't be read."""
    path = _state_path()
    if not path.exists():
        return {}
    try:
        state = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as e:
        raise Unreadable(f"{path} can't be read ({e})") from e
    if not isinstance(state, dict):
        raise Unreadable(f"{path} isn't a JSON object")
    return state


def set_aside_state() -> Path:
    """Move an unreadable sync-state.json aside, named by the UTC time, and say where."""
    path = _state_path()
    bad = path.with_name(f"sync-state.{datetime.now(UTC):%Y%m%dT%H%M%SZ}.bad.json")
    path.replace(bad)
    return bad


def _save_state(state: dict) -> None:
    """Whole or not at all: a run cut off mid-write leaves the last state."""
    path = _state_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + ".part")
    tmp.write_text(json.dumps(state, indent=1), encoding="utf-8")
    tmp.replace(path)


def append_version(log_dir: Path, deck: Deck, catalog: Catalog, today: str, state: dict) -> bool:
    """Append a +/- diff when a deck's list changed since the last sync, and record the new
    list in state (see load_state), saved at once so the log and the state move together."""
    legacy = log_dir / f"{deck.slug}.versions.md"
    if legacy.exists() and not (log_dir / f"{deck.slug}-versions.md").exists():
        legacy.rename(log_dir / f"{deck.slug}-versions.md")
    cards: Counter[str] = Counter()
    for e in deck.entries:
        cards[catalog.name(e.card_id) if e.card_id else e.name] += e.quantity
    digest = hashlib.sha256(json.dumps(sorted(cards.items())).encode()).hexdigest()[:16]
    prev = state.get(deck.slug)
    if prev and prev["hash"] == digest:
        return False
    log = log_dir / f"{deck.slug}-versions.md"
    log_dir.mkdir(parents=True, exist_ok=True)
    if not log.exists():
        log.write_text(
            f"---\ntitle: {deck.slug}-versions\ntype: log\ndeck: {deck.slug}\n---\n\n"
            "Appended by `riffle sync` when the list changes. Never edit.\n",
            encoding="utf-8",
        )
    with log.open("a", encoding="utf-8") as f:
        if prev is None:
            f.write(f"\n## {today}\n\nBaseline: {sum(cards.values())} cards.\n")
        else:
            old = Counter(prev["cards"])
            added, removed = cards - old, old - cards
            f.write(f"\n## {today}\n\n")
            f.writelines(f"- \\+ {n} [[{c}]]\n" for c, n in sorted(added.items()))
            f.writelines(f"- \\- {n} [[{c}]]\n" for c, n in sorted(removed.items()))
    state[deck.slug] = {"hash": digest, "cards": dict(cards)}
    _save_state(state)
    return True


def write_deck(gen_dir: Path, deck: Deck, text: str) -> bool:
    return _write(gen_dir / f"{deck.slug}-data.md", text)


def prune(gen_dir: Path, keep: set[str]) -> list[str]:
    """_generated/ is repo-owned: remove notes this sync didn't produce."""
    removed = []
    for p in gen_dir.glob("*.md"):
        if p.name not in keep and p.name != "README.md":
            p.unlink()
            removed.append(p.name)
    return removed


def write_summary(gen_dir: Path, text: str) -> bool:
    return _write(gen_dir / "collection-summary.md", text)


def today() -> str:
    return date.today().isoformat()
