"""Write the vault's machine zones. Nothing else in the vault is touched.

In the notes folder (config's notes):

    mtg/_generated/<deck>-data.md    rebuilt every sync, written when it changed; stale ones removed
    mtg/_generated/collection-summary.md
    mtg/_log/<deck>-versions.md      append-only, only when a list changes
    mtg/_log/prices.md               no longer appended: `riffle prices log` reads the store

Every file is written whole (a temporary file renamed over it), so a sync service never
uploads half a note.

Authored notes pull generated ones in with ![[aesi-lands-data]]. No dots in
generated names: Obsidian reads "aesi-lands.data" as a ".data" file.
"""

import hashlib
import json
from collections import Counter
from datetime import UTC, datetime
from pathlib import Path

from riffle import times
from riffle.analysis.ownership import BUY, MARK, OWN, Row, summary
from riffle.analysis.pricing import DeckPrice
from riffle.config import data_dir
from riffle.models import Deck, Holding, Prices
from riffle.store import Catalog


def _money(x: float | None) -> str:
    return f"${x:,.2f}" if x is not None else "—"


def _tix(x: float | None) -> str:
    return f"{x:,.2f}" if x is not None else "—"


def _write(path: Path, text: str) -> bool:
    """Write only if different, so a sync service doesn't upload unchanged files, and whole:
    a sync service or Obsidian reading the note mid-write sees the old one, never half."""
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    tmp = path.with_name(f".{path.name}.part")
    try:
        tmp.write_text(text, encoding="utf-8")
        tmp.replace(path)
    except BaseException:
        tmp.unlink(missing_ok=True)
        raise
    return True


def deck_data(
    deck: Deck,
    rows: list[Row],
    dp: DeckPrice,
    unresolved: list[str],
    imports: dict[str, str] | None = None,
) -> str:
    """A deck's generated note. It holds no date, so it changes only when what it says does."""
    s = summary(rows)
    buy = [(row, line) for row, line in zip(rows, dp.lines, strict=True) if row.status == BUY]
    out = [
        "---",
        f"title: {deck.slug}-data",
        "type: generated",
        f"deck: {deck.slug}",
        "---",
        "",
        "> [!warning] Generated by `riffle sync` — edits here are overwritten",
        "",
        f"**{deck.count()} cards** · {MARK[OWN]} {s[OWN]} own · {MARK[BUY]} {s[BUY]} buy",
        "",
        "| | Paper | MTGO |",
        "|---|---|---|",
        f"| Whole deck | {_money(dp.usd_total)} | {_tix(dp.tix_total)} tix |",
        f"| Still to buy | {_money(dp.usd_to_buy)} | — |",
        "",
    ]
    if buy:
        out += ["## Buy", "", "| Buy | Card | Paper | MTGO |", "|---|---|---|---|"]
        for row, line in sorted(buy, key=lambda pair: -(pair[1].usd or 0)):
            note = f" (own {row.owned} of {row.needed})" if row.partial else ""
            out.append(
                f"| {MARK[BUY]} {row.shortfall} | [[{row.name}]]{note} "
                f"| {_money(line.usd)} | {_tix(line.tix)} |"
            )
        out.append("")
    if dp.missing_on_mtgo:
        out += ["## Not on MTGO", "", ", ".join(f"[[{n}]]" for n in dp.missing_on_mtgo), ""]
    if unresolved:
        out += ["> [!bug] Names that didn't match any card", "> " + ", ".join(unresolved), ""]
    for title, text in (imports or {}).items():
        out += [f"## {title}", "", "```", text.rstrip(), "```", ""]
    return "\n".join(out)


def collection_summary(holdings: list[Holding], catalog: Catalog) -> str:
    counted: list[tuple[str, Holding]] = []
    for h in holdings:
        if h.source == "manabox" and h.card_id:
            counted.append((h.card_id, h))
    total = sum(h.quantity for _, h in counted)
    unique = len({card_id for card_id, _ in counted})
    printed = catalog.printings({h.scryfall_id for _, h in counted if h.scryfall_id})
    own_price = [p.usd if (p := printed.get(h.scryfall_id or "")) else None for _, h in counted]
    cheapest = catalog.prices(
        {card_id for (card_id, _), usd in zip(counted, own_price, strict=True) if usd is None}
    )
    valued = []
    for (card_id, h), usd in zip(counted, own_price, strict=True):
        if usd is None:  # no price for the printing owned: value it as the card's cheapest
            usd = cheapest.get(card_id, Prices()).usd
        valued.append((usd or 0) * h.quantity)
    top = sorted(zip(valued, counted, strict=True), key=lambda x: -x[0])[:15]
    lines = [
        "---",
        "title: collection-summary",
        "type: generated",
        "---",
        "",
        "> [!warning] Generated by `riffle sync` — edits here are overwritten",
        "",
        f"**{total:,} cards · {unique:,} unique · ~{_money(sum(valued))}** (ManaBox export)",
        "",
    ]
    lines += ["## Most valuable", "", "| Card | Copies | Value |", "|---|---|---|"]
    lines += [f"| [[{catalog.name(card_id)}]] | {h.quantity} | {_money(v)} |" for v, (card_id, h) in top]
    return "\n".join(lines) + "\n"


def price_line(day: str, name: str, prices: Prices) -> str:
    """`date | card | paper | tix`, as _log/prices.md has it."""
    return f"{day} | {name} | {_money(prices.usd)} | {_tix(prices.tix)}"


CONTINUES = "`riffle prices log`"


def close_price_log(log: Path, today: str) -> bool:
    """End the price log the sync appended to until 0.4.0 with a line saying where its history
    continues. Once: False when there's no log, or it ends so already."""
    if not log.exists():
        return False
    text = log.read_text(encoding="utf-8")
    if CONTINUES in text:
        return False
    end = (
        f"\nNot appended to since {today}: {CONTINUES} prints every buy card's price for each "
        "Scryfall day the store keeps.\n"
    )
    return _write(log, text + ("" if text.endswith("\n") else "\n") + end)


def _state_path() -> Path:
    return data_dir() / "sync-state.json"


class Unreadable(ValueError):
    """sync-state.json is there but can't be read."""


def load_state() -> dict:
    """Each deck's list at the last sync that logged it, by slug: what version logs diff
    against. Empty before the first sync; Unreadable if the file can't be read."""
    path = _state_path()
    if not path.exists():
        return {}
    try:
        state = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as e:
        raise Unreadable(f"{path} can't be read ({e})") from e
    if not isinstance(state, dict):
        raise Unreadable(f"{path} isn't a JSON object")
    return state


def set_aside_state() -> Path:
    """Move an unreadable sync-state.json aside, named by the UTC time, and say where."""
    path = _state_path()
    bad = path.with_name(f"sync-state.{datetime.now(UTC):%Y%m%dT%H%M%SZ}.bad.json")
    path.replace(bad)
    return bad


def save_state(state: dict) -> None:
    """Whole or not at all: a run cut off mid-write leaves the last state."""
    path = _state_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + ".part")
    tmp.write_text(json.dumps(state, indent=1), encoding="utf-8")
    tmp.replace(path)


def append_version(log_dir: Path, deck: Deck, catalog: Catalog, today: str, state: dict) -> bool:
    """Append a +/- diff when a deck's list changed since the last sync, and record the new
    list in state (see load_state). The caller saves the state once, after the last deck."""
    legacy = log_dir / f"{deck.slug}.versions.md"
    if legacy.exists() and not (log_dir / f"{deck.slug}-versions.md").exists():
        legacy.rename(log_dir / f"{deck.slug}-versions.md")
    cards: Counter[str] = Counter()
    for e in deck.entries:
        cards[catalog.name(e.card_id) if e.card_id else e.name] += e.quantity
    digest = hashlib.sha256(json.dumps(sorted(cards.items())).encode()).hexdigest()[:16]
    prev = state.get(deck.slug)
    if prev and prev["hash"] == digest:
        return False
    log = log_dir / f"{deck.slug}-versions.md"
    if log.exists():
        text = log.read_text(encoding="utf-8")
    else:
        text = (
            f"---\ntitle: {deck.slug}-versions\ntype: log\ndeck: {deck.slug}\n---\n\n"
            "Appended by `riffle sync` when the list changes. Never edit.\n"
        )
    if prev is None:
        text += f"\n## {today}\n\nBaseline: {sum(cards.values())} cards.\n"
    else:
        old = Counter(prev["cards"])
        added, removed = cards - old, old - cards
        text += f"\n## {today}\n\n"
        text += "".join(f"- \\+ {n} [[{c}]]\n" for c, n in sorted(added.items()))
        text += "".join(f"- \\- {n} [[{c}]]\n" for c, n in sorted(removed.items()))
    _write(log, text)
    state[deck.slug] = {"hash": digest, "cards": dict(cards)}
    return True


def write_deck(gen_dir: Path, deck: Deck, text: str) -> bool:
    return _write(gen_dir / f"{deck.slug}-data.md", text)


def prune(gen_dir: Path, keep: set[str]) -> list[str]:
    """_generated/ is repo-owned: remove notes this sync didn't produce."""
    removed = []
    for p in gen_dir.glob("*.md"):
        if p.name not in keep and p.name != "README.md":
            p.unlink()
            removed.append(p.name)
    return removed


def write_summary(gen_dir: Path, text: str) -> bool:
    return _write(gen_dir / "collection-summary.md", text)


def today() -> str:
    """Today's date in UTC, as the notes are dated."""
    return times.today().isoformat()
